name = "cf-ai-chat"
main = "src/worker.ts"
compatibility_date = "2024-06-01"

[vars]
CF_TOKEN = ""
CF_GATEWAY = ""
OPENAI_API_KEY = ""
OPENAI_API_URL = ""
G_API_KEY = ""
G_API_URL = ""
PASSWORD = ""